### ISSUE TITLE
Text isn't selectable

### ISSUE THREAD

**Issue by easrng** [thesephist/plume#1]
Not all text is selectable. At least the chat should be.

**Comment by thesephist** [comment]
Thanks for pointing it out! This was an issue created by [blocks.css](https://thesephist.github.io/blocks.css/) setting`-webkit-user-select:none` on all block-y elements. We just overrode it in plume.chat's styles.

<img width="845" alt="Screen Shot 2020-06-22 at 17 11 44" src="https://user-images.githubusercontent.com/5403917/85335720-73987500-b4ab-11ea-911f-a654fbe9a442.png">
